version: '3.3'

services:
  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio-object-storage
    ports:
      - '19000:9000'
      - '19001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local